#reset
update ingredients set carbon_foot_print = null, carbon_foot_print_source = null, carbon_foot_print_weight = null, water_foot_print = null, water_foot_print_source = null, water_foot_print_weight = null where 1 = 1;

delete from ingredients_name_alias where 1 = 1;

#FIRST BLOCK OF UPDATES, HERE THE EMBEDDING BASED COMPARISON DONE A GOOD JOB.######################################################################
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =3;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =6;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1140, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =10;
update ingredients set carbon_foot_print =0.93, water_foot_print = 1378, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =12;
update ingredients set carbon_foot_print =11.21, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =13;
update ingredients set carbon_foot_print =0.22, water_foot_print = 290, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =16;
update ingredients set carbon_foot_print =0.84, water_foot_print = 1657, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =17;
update ingredients set carbon_foot_print =1.11, water_foot_print = 2750, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =19;
update ingredients set carbon_foot_print =3.37, water_foot_print = 2193, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =22;
update ingredients set carbon_foot_print =0.88, water_foot_print = 9371, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =24;
update ingredients set carbon_foot_print =0.25, water_foot_print = 272, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =25;
update ingredients set carbon_foot_print =0.64, water_foot_print = 3015, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =27;
update ingredients set carbon_foot_print =0.84, water_foot_print = 1657, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =30;
update ingredients set carbon_foot_print =0.64, water_foot_print = 499, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =31;
update ingredients set carbon_foot_print =0.31, water_foot_print = 608, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =32;
update ingredients set carbon_foot_print =0.36, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =33;
update ingredients set carbon_foot_print =4.3, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =35;
update ingredients set carbon_foot_print =0.32, water_foot_print = 185, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =36;
update ingredients set carbon_foot_print =1.03, water_foot_print = 713, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =40;
update ingredients set carbon_foot_print =3.68, water_foot_print = 3960, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =47;
update ingredients set carbon_foot_print =0.94, water_foot_print = 865, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =48;
update ingredients set carbon_foot_print =0.54, water_foot_print = 2030, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =52;
update ingredients set carbon_foot_print =8.93, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =56;
update ingredients set carbon_foot_print =0.57, water_foot_print = 1639, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =58;
update ingredients set carbon_foot_print =1.39, water_foot_print = 1324, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =63;
update ingredients set carbon_foot_print =4.3, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =65;
update ingredients set carbon_foot_print =0.54, water_foot_print = 362, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =66;
update ingredients set carbon_foot_print =2.19, water_foot_print = 1597, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =68;
update ingredients set carbon_foot_print =0.52, water_foot_print = 5874, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =71;
update ingredients set carbon_foot_print =2.27, water_foot_print = 1724, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =76;
update ingredients set carbon_foot_print =5.19, water_foot_print = 2313.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =80;
update ingredients set carbon_foot_print =0.33, water_foot_print = 362, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =82;
update ingredients set carbon_foot_print =0.27, water_foot_print = 383, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =85;
update ingredients set carbon_foot_print =2.06, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =90;
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =91;
update ingredients set carbon_foot_print =3.27, water_foot_print = 14415, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =94;
update ingredients set carbon_foot_print =1.6, water_foot_print = 11363, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =96;
update ingredients set carbon_foot_print =0.67, water_foot_print = 1788, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =97;
update ingredients set carbon_foot_print =4.3, water_foot_print = 17196, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =102;
update ingredients set carbon_foot_print =2.72, water_foot_print = 2174, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =104;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =106;
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =107;
update ingredients set carbon_foot_print =2.06, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =108;
update ingredients set carbon_foot_print =1.84, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =114;
update ingredients set carbon_foot_print =0.49, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =122;
update ingredients set carbon_foot_print =0.27, water_foot_print = 922, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =123;
update ingredients set carbon_foot_print =5.45, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =128;
update ingredients set carbon_foot_print =8.2, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =130;
update ingredients set carbon_foot_print =0.22, water_foot_print = 290, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =133;
update ingredients set carbon_foot_print =0.46, water_foot_print = 1506.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =137;
update ingredients set carbon_foot_print =0.83, water_foot_print = 2150, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =142;
update ingredients set carbon_foot_print =0.57, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =143;
update ingredients set carbon_foot_print =1.48, water_foot_print = 807, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =146;
update ingredients set carbon_foot_print =0.25, water_foot_print = 195, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =152;
update ingredients set carbon_foot_print =1.88, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =156;
update ingredients set carbon_foot_print =2.06, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =158;
update ingredients set carbon_foot_print =0.47, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =166;
update ingredients set carbon_foot_print =0.62, water_foot_print = 1724, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =168;
update ingredients set carbon_foot_print =0.87, water_foot_print = 2536, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =171;
update ingredients set carbon_foot_print =0.52, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =173;
update ingredients set carbon_foot_print =0.32, water_foot_print = 2180, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =176;
update ingredients set carbon_foot_print =3.29, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =180;
update ingredients set carbon_foot_print =3.68, water_foot_print = 3960, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =182;
update ingredients set carbon_foot_print =0.52, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =183;
update ingredients set carbon_foot_print =4.3, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =184;
update ingredients set carbon_foot_print =5.45, water_foot_print = 2470.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =190;
update ingredients set carbon_foot_print =0.87, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =192;
update ingredients set carbon_foot_print =2.13, water_foot_print = 3330.3, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =194;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1273, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =195;
update ingredients set carbon_foot_print =0.31, water_foot_print = 285, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =197;
update ingredients set carbon_foot_print =0.81, water_foot_print = 2636.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =201;
update ingredients set carbon_foot_print =1.38, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =202;
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =205;
update ingredients set carbon_foot_print =0.3, water_foot_print = 1287, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =206;
update ingredients set carbon_foot_print =0.24, water_foot_print = 555, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =208;
update ingredients set carbon_foot_print =0.39, water_foot_print = 910, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =209;
update ingredients set carbon_foot_print =0.32, water_foot_print = 3350, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =219;
update ingredients set carbon_foot_print =2.06, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =222;
update ingredients set carbon_foot_print =1.39, water_foot_print = 1324, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =227;
update ingredients set carbon_foot_print =0.87, water_foot_print = 2536, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =229;
update ingredients set carbon_foot_print =0.28, water_foot_print = 255, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =231;
update ingredients set carbon_foot_print =0.64, water_foot_print = 276, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =233;
update ingredients set carbon_foot_print =5.99, water_foot_print = 6177, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =238;
update ingredients set carbon_foot_print =3.44, water_foot_print = 4361, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =246;
update ingredients set carbon_foot_print =0.33, water_foot_print = 362, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =248;
update ingredients set carbon_foot_print =0.33, water_foot_print = 818, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =250;
update ingredients set carbon_foot_print =17.96, water_foot_print = 10943, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =252;
update ingredients set carbon_foot_print =2.85, water_foot_print = 1540, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =254;
update ingredients set carbon_foot_print =1.11, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =255;
update ingredients set carbon_foot_print =3.2, water_foot_print = 2562, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =258;
update ingredients set carbon_foot_print =0.97, water_foot_print = 1618, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =259;
update ingredients set carbon_foot_print =0.52, water_foot_print = 4177, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =260;
update ingredients set carbon_foot_print =0.78, water_foot_print = 2030, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =264;
update ingredients set carbon_foot_print =7.04, water_foot_print = 1856, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =266;
update ingredients set carbon_foot_print =5.99, water_foot_print = 6116, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =269;
update ingredients set carbon_foot_print =0.49, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =272;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =277;
update ingredients set carbon_foot_print =5.45, water_foot_print = 3838, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =281;
update ingredients set carbon_foot_print =0.22, water_foot_print = 290, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =282;
update ingredients set carbon_foot_print =1.74, water_foot_print = null, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =283;
update ingredients set carbon_foot_print =0.78, water_foot_print = 845, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =286;
update ingredients set carbon_foot_print =8.48, water_foot_print = 5659, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =293;
update ingredients set carbon_foot_print =0.46, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =296;
update ingredients set carbon_foot_print =3.44, water_foot_print = 4361, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =297;
update ingredients set carbon_foot_print =2.19, water_foot_print = 1597, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =299;
update ingredients set carbon_foot_print =1.39, water_foot_print = 1324, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =300;
update ingredients set carbon_foot_print =0.62, water_foot_print = 1724, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =304;
update ingredients set carbon_foot_print =0.34, water_foot_print = 292, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =308;
update ingredients set carbon_foot_print =0.81, water_foot_print = 2636.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =312;
update ingredients set carbon_foot_print =0.48, water_foot_print = 1423, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =314;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3366, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =319;
update ingredients set carbon_foot_print =0.25, water_foot_print = 272, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =322;
update ingredients set carbon_foot_print =3.68, water_foot_print = 3960, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =326;
update ingredients set carbon_foot_print =8.48, water_foot_print = 5659, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =327;
update ingredients set carbon_foot_print =0.24, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =334;
update ingredients set carbon_foot_print =0.24, water_foot_print = 195, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =338;
update ingredients set carbon_foot_print =25.75, water_foot_print = 15139, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =512;
update ingredients set carbon_foot_print =25.75, water_foot_print = 15139, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =513;
update ingredients set carbon_foot_print =0.87, water_foot_print = 2536, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =514;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =519;
update ingredients set carbon_foot_print =0.52, water_foot_print = 555.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =228;
update ingredients set carbon_foot_print =0.61, water_foot_print = 1506.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =310;
update ingredients set carbon_foot_print =0.7, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =340;
update ingredients set carbon_foot_print =0.61, water_foot_print = 1506.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =139;

insert into ingredients_name_alias values (3,'DARK CHOCOLATE');
insert into ingredients_name_alias values (6,'GOAT CHEESE');
insert into ingredients_name_alias values (10,'APPLE JUICE');
insert into ingredients_name_alias values (12,'FLAVORED CRACKERS');
insert into ingredients_name_alias values (13,'CEDDAR');
insert into ingredients_name_alias values (16,'ONION');
insert into ingredients_name_alias values (17,'GINGER');
insert into ingredients_name_alias values (19,'CHESTNUT');
insert into ingredients_name_alias values (22,'SALMON');
insert into ingredients_name_alias values (24,'SESAM SEED');
insert into ingredients_name_alias values (25,'RADISH');
insert into ingredients_name_alias values (27,'OLIVES');
insert into ingredients_name_alias values (30,'GINGER');
insert into ingredients_name_alias values (31,'CURRANT');
insert into ingredients_name_alias values (32,'GRAPES');
insert into ingredients_name_alias values (33,'WHOLE WHEAT FLOUR');
insert into ingredients_name_alias values (35,'ICE CREAM');
insert into ingredients_name_alias values (36,'WATERMELON');
insert into ingredients_name_alias values (40,'TOMATO PUREE');
insert into ingredients_name_alias values (47,'CHICKEN BONE FREE MEAT');
insert into ingredients_name_alias values (48,'BEET SUGAR');
insert into ingredients_name_alias values (52,'ALMOND MILK');
insert into ingredients_name_alias values (56,'CHEESE');
insert into ingredients_name_alias values (58,'WHEAT');
insert into ingredients_name_alias values (63,'MARGARINE');
insert into ingredients_name_alias values (65,'ICE CREAM');
insert into ingredients_name_alias values (66,'VEGETABLES');
insert into ingredients_name_alias values (68,'RICE');
insert into ingredients_name_alias values (71,'LENTIL');
insert into ingredients_name_alias values (76,'TOFU');
insert into ingredients_name_alias values (80,'CATFISH');
insert into ingredients_name_alias values (82,'FENNEL');
insert into ingredients_name_alias values (85,'SWEET POTATO');
insert into ingredients_name_alias values (90,'MUSHROOM');
insert into ingredients_name_alias values (91,'DARK CHOCOLATE');
insert into ingredients_name_alias values (94,'OLIVE OIL');
insert into ingredients_name_alias values (96,'PISTACHIO');
insert into ingredients_name_alias values (97,'OAT');
insert into ingredients_name_alias values (102,'CHOCOLATE');
insert into ingredients_name_alias values (104,'PESTO');
insert into ingredients_name_alias values (106,'MANGO JUICE');
insert into ingredients_name_alias values (107,'MILK CHOCOLATE');
insert into ingredients_name_alias values (108,'WALNUT');
insert into ingredients_name_alias values (114,'PEANUT BUTTER');
insert into ingredients_name_alias values (122,'MINERAL WATER');
insert into ingredients_name_alias values (123,'PEAR');
insert into ingredients_name_alias values (128,'MASCARPONE');
insert into ingredients_name_alias values (130,'MOZZARELLA');
insert into ingredients_name_alias values (133,'ONION');
insert into ingredients_name_alias values (137,'CHERRY');
insert into ingredients_name_alias values (142,'ASPARAGUS');
insert into ingredients_name_alias values (143,'BROCCOLI');
insert into ingredients_name_alias values (146,'CORN CANNED');
insert into ingredients_name_alias values (152,'TURNIP');
insert into ingredients_name_alias values (156,'ALMOND');
insert into ingredients_name_alias values (158,'MUSHROOM');
insert into ingredients_name_alias values (166,'DURUM WHEAT');
insert into ingredients_name_alias values (168,'CANE SUGAR');
insert into ingredients_name_alias values (171,'OAT MEAL');
insert into ingredients_name_alias values (173,'WHEAT PLAIN FLOUR');
insert into ingredients_name_alias values (176,'PLUM');
insert into ingredients_name_alias values (180,'YEAST DRIED');
insert into ingredients_name_alias values (182,'CHICKEN BONE FREE MEAT');
insert into ingredients_name_alias values (183,'WHEAT PLAIN FLOUR');
insert into ingredients_name_alias values (184,'ICE CREAM');
insert into ingredients_name_alias values (190,'RICOTTA');
insert into ingredients_name_alias values (192,'SORGHUM FLOUR');
insert into ingredients_name_alias values (194,'TURKEY MEAT WITH BONE');
insert into ingredients_name_alias values (195,'PINEAPPLE JUICE');
insert into ingredients_name_alias values (197,'CAULIFLOWER');
insert into ingredients_name_alias values (201,'DATE');
insert into ingredients_name_alias values (202,'CASHEW NUT');
insert into ingredients_name_alias values (205,'DARK CHOCOLATE');
insert into ingredients_name_alias values (206,'APRICOT');
insert into ingredients_name_alias values (208,'POTATO');
insert into ingredients_name_alias values (209,'PEACH');
insert into ingredients_name_alias values (219,'FIG');
insert into ingredients_name_alias values (222,'MUSHROOM');
insert into ingredients_name_alias values (227,'MARGARINE');
insert into ingredients_name_alias values (229,'OAT MEAL');
insert into ingredients_name_alias values (231,'PINEAPPLE');
insert into ingredients_name_alias values (233,'CRANBERRY');
insert into ingredients_name_alias values (238,'PORK SAUSAGES');
insert into ingredients_name_alias values (246,'PORK MEAT WITH BONE');
insert into ingredients_name_alias values (248,'CELERY');
insert into ingredients_name_alias values (250,'ARTICHOKE');
insert into ingredients_name_alias values (252,'BEEF MEAT WITH BONE');
insert into ingredients_name_alias values (254,'YOGURT FLAVOURED');
insert into ingredients_name_alias values (255,'HAZELNUT');
insert into ingredients_name_alias values (258,'EGGS');
insert into ingredients_name_alias values (259,'QUINOA');
insert into ingredients_name_alias values (260,'CHICKPEA');
insert into ingredients_name_alias values (264,'SOY MILK');
insert into ingredients_name_alias values (266,'PRAWNS/SHRIMPS');
insert into ingredients_name_alias values (269,'BACON');
insert into ingredients_name_alias values (272,'MINERAL WATER');
insert into ingredients_name_alias values (277,'CRANBERRY JUICE');
insert into ingredients_name_alias values (281,'CREAM');
insert into ingredients_name_alias values (282,'ONION');
insert into ingredients_name_alias values (283,'HONEY');
insert into ingredients_name_alias values (286,'BLUEBERRY');
insert into ingredients_name_alias values (293,'BUTTER');
insert into ingredients_name_alias values (296,'ORANGE JUICE');
insert into ingredients_name_alias values (297,'PORK MEAT WITH BONE');
insert into ingredients_name_alias values (299,'RICE');
insert into ingredients_name_alias values (300,'MARGARINE');
insert into ingredients_name_alias values (304,'CANE SUGAR');
insert into ingredients_name_alias values (308,'SPINACH');
insert into ingredients_name_alias values (312,'RAISIN');
insert into ingredients_name_alias values (314,'BARLEY');
insert into ingredients_name_alias values (319,'SUNFLOWER SEED');
insert into ingredients_name_alias values (322,'BEETROOT');
insert into ingredients_name_alias values (326,'CHICKEN BONE FREE MEAT');
insert into ingredients_name_alias values (327,'BUTTER');
insert into ingredients_name_alias values (334,'PUMPKIN');
insert into ingredients_name_alias values (338,'CARROT');
insert into ingredients_name_alias values (512,'BEEF BONE FREE MEAT');
insert into ingredients_name_alias values (513,'BEEF BONE FREE MEAT');
insert into ingredients_name_alias values (514,'OAT MEAL');
insert into ingredients_name_alias values (519,'MAYONNAISE');
insert into ingredients_name_alias values (228,'GREEN BEAN');
insert into ingredients_name_alias values (310,'MELON');
insert into ingredients_name_alias values (340,'ZUCCHINI');
insert into ingredients_name_alias values (139,'MELON');#CANTALOUPE

#THESE INGREDIENTS (CHOSEN USING THE OPENFIELD VERSION IF AVAILABLE) (STILL DERIVED FROM THE PREVIOUS MATCHES) EXISTS ALSO IN THE IMPORTED/GREENHOUSE VERSION, THESE ALTERNATIVE VERSION WILL BE ADDED AS INSERT
update ingredients set carbon_foot_print =0.45, water_foot_print = 41, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =5;
update ingredients set carbon_foot_print =0.41, water_foot_print = 237, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =105;
update ingredients set carbon_foot_print =0.27, water_foot_print = 353, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =153;
update ingredients set carbon_foot_print =0.34, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =170;
update ingredients set carbon_foot_print =0.61, water_foot_print = 413, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =188;
update ingredients set carbon_foot_print =0.54, water_foot_print = 1805, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =224;
update ingredients set carbon_foot_print =0.65, water_foot_print = 379, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =235;
update ingredients set carbon_foot_print =0.65, water_foot_print = 379, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =243;
update ingredients set carbon_foot_print =0.33, water_foot_print =336.0, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =330;
update ingredients set carbon_foot_print =1.19, water_foot_print =151.3, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =43;
update ingredients set carbon_foot_print =0.84, water_foot_print =8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =237;
update ingredients set carbon_foot_print =0.64, water_foot_print =413, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =193;
update ingredients set carbon_foot_print =0.87, water_foot_print =1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =236;
update ingredients set carbon_foot_print =2.12, water_foot_print =2313.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =316;
update ingredients set carbon_foot_print =1.46, water_foot_print =572.0, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =279;

insert into ingredients_name_alias values (5,'TOMATO');
insert into ingredients_name_alias values (105,'LETTUCE');
insert into ingredients_name_alias values (153,'CUCUMBER');
insert into ingredients_name_alias values (170,'BANANA');
insert into ingredients_name_alias values (188,'STRAWBERRY');
insert into ingredients_name_alias values (224,'AVOCADO');
insert into ingredients_name_alias values (235,'JALAPENO PEPPER'); #JALAPENO
insert into ingredients_name_alias values (243,'PEPPER');
insert into ingredients_name_alias values (330,'RADICCHIO');
insert into ingredients_name_alias values (43,'MARINARA SAUCE');
insert into ingredients_name_alias values (237,'TACO SEASONING');
insert into ingredients_name_alias values (193,'RASPBERRY');
insert into ingredients_name_alias values (236,'SEMOLINA');
insert into ingredients_name_alias values (316,'SURIMI');
insert into ingredients_name_alias values (279,'HORSERADISH');
#####################################################################################################################################################

#more matches from sueatable founded adding rows from the wfp sheet######################################################################
update ingredients set carbon_foot_print =5.19, water_foot_print = 2263, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =7;
update ingredients set carbon_foot_print =0.69, water_foot_print = 155, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =50;
update ingredients set carbon_foot_print =0.33, water_foot_print = 576, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =67;
update ingredients set carbon_foot_print =0.25, water_foot_print = 272, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =73;
update ingredients set carbon_foot_print =0.32, water_foot_print = 460, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =163;
update ingredients set carbon_foot_print =0.33, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =251;
update ingredients set carbon_foot_print =2.86, water_foot_print = 675, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =321;
update ingredients set carbon_foot_print =0.27, water_foot_print = 2818, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =15;
update ingredients set carbon_foot_print =0.78, water_foot_print = 527, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =26;
update ingredients set carbon_foot_print =1.44, water_foot_print = 1599, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =120;
update ingredients set carbon_foot_print =1.46, water_foot_print = 534, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =140;
update ingredients set carbon_foot_print =0.78, water_foot_print = 527, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =199;
update ingredients set carbon_foot_print =0.33, water_foot_print = 285, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =230;
update ingredients set carbon_foot_print =0.87, water_foot_print = 2429, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =262;
update ingredients set carbon_foot_print =0.84, water_foot_print = 288, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =324;
update ingredients set carbon_foot_print =3.16, water_foot_print = 15618, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =336;
update ingredients set carbon_foot_print =0.88, water_foot_print = 2188, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =109;
update ingredients set carbon_foot_print =0.84, water_foot_print = 2265, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =157;
update ingredients set carbon_foot_print =1.46, water_foot_print = 613, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =189;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =207;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =211;
update ingredients set carbon_foot_print =0.84, water_foot_print = 15526, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =268;
update ingredients set carbon_foot_print =0.84, water_foot_print = 731000, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =271;
update ingredients set carbon_foot_print =1.46, water_foot_print = 613, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =280;
update ingredients set carbon_foot_print =0.84, water_foot_print = 34319, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =303;
update ingredients set carbon_foot_print =0.84, water_foot_print = 61205, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =306;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =329;
update ingredients set carbon_foot_print =0.84, water_foot_print = 34319, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =332;

insert into ingredients_name_alias values (7,'TILAPIA');
insert into ingredients_name_alias values (50,'BEER');
insert into ingredients_name_alias values (67,'OKRA');
insert into ingredients_name_alias values (73,'SHALLOT');
insert into ingredients_name_alias values (163,'PAPAYA');
insert into ingredients_name_alias values (251,'SQUASH');
insert into ingredients_name_alias values (321,'GRAPEFRUIT JUICE');
insert into ingredients_name_alias values (15,'TAPIOCA OF CASSAVA');
insert into ingredients_name_alias values (26,'CANE MOLASSE');
insert into ingredients_name_alias values (120,'BUTTERED MILK');
insert into ingredients_name_alias values (140,'KETCHUP');
insert into ingredients_name_alias values (199,'CANE MOLASSE');
insert into ingredients_name_alias values (230,'BRUSSEL SPROUT');
insert into ingredients_name_alias values (262,'RICE FLOUR & MEAL');
insert into ingredients_name_alias values (324,'PEPPERMINT');
insert into ingredients_name_alias values (336,'COCOA POWDER');
insert into ingredients_name_alias values (109,'POPPY SEED');
insert into ingredients_name_alias values (157,'GARLIC POWDER');
insert into ingredients_name_alias values (189,'SOY SAUCE');
insert into ingredients_name_alias values (207,'FENNEL SEEDS');
insert into ingredients_name_alias values (211,'ANISE');
insert into ingredients_name_alias values (268,'CINNAMON');
insert into ingredients_name_alias values (271,'SAFFRON');
insert into ingredients_name_alias values (280,'SOY SAUCE');
insert into ingredients_name_alias values (303,'NUTMEG');
insert into ingredients_name_alias values (306,'CLOVE');
insert into ingredients_name_alias values (329,'CORIANDER');
insert into ingredients_name_alias values (332,'CARDAMOM');

#added later manually INGREDIENT PRESENT IN SUEATABLE WITHOUT MATCH FOR THE ALGORITHM######################################################################
update ingredients set carbon_foot_print =0.52, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =9;
update ingredients set carbon_foot_print =0.23, water_foot_print = 280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =28;
update ingredients set carbon_foot_print =0.64, water_foot_print = 413, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =70;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =117;
update ingredients set carbon_foot_print =1.31, water_foot_print = 1260.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =164;
update ingredients set carbon_foot_print =0.45, water_foot_print = 1979, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =234;
update ingredients set carbon_foot_print =0.87, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =241;
update ingredients set carbon_foot_print =3.08, water_foot_print = 2782, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =273;
update ingredients set carbon_foot_print =0.25, water_foot_print = 622, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =285;
update ingredients set carbon_foot_print =0.34, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =315;
update ingredients set carbon_foot_print =1.44, water_foot_print = 1599, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =187;
update ingredients set carbon_foot_print =0.87, water_foot_print = 1889.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =57;
update ingredients set carbon_foot_print =0.43, water_foot_print = 5053, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =38;
update ingredients set carbon_foot_print =5.45, water_foot_print = 3838, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =103;

insert into ingredients_name_alias values (9,'WHEAT PLAIN FLOUR');
insert into ingredients_name_alias values (28,'CABAGGE');
insert into ingredients_name_alias values (70,'BLACKBERRY');
insert into ingredients_name_alias values (117,'PARMIGIANO REGGIANO');
insert into ingredients_name_alias values (164,'COW MILK');
insert into ingredients_name_alias values (234,'PEA');
insert into ingredients_name_alias values (241,'MAIZE FLOUR');
insert into ingredients_name_alias values (273,'COD');
insert into ingredients_name_alias values (285,'APPLE');
insert into ingredients_name_alias values (315,'TANGERIN');
insert into ingredients_name_alias values (187,'CONDENSED MILK');
insert into ingredients_name_alias values (57,'CORNMEAL');
insert into ingredients_name_alias values (38,'BEANS');
insert into ingredients_name_alias values (103,'CREAM');

#ADDED MANUALLY CFP AND WFP BASED ON MEDIAN VALUES OF SUEATABLE TYPOLOGIES OR SUB-TYPOLOGY######################################################################
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =1;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =11;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5060, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =121;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =160;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =177;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =212;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =320;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =178;
update ingredients set carbon_foot_print =1.19, water_foot_print = 151.3, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =305;
update ingredients set carbon_foot_print =0.25, water_foot_print = 272, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =41;
update ingredients set carbon_foot_print =0.25, water_foot_print = 272, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =60;
update ingredients set carbon_foot_print =0.40, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =18;
update ingredients set carbon_foot_print =9.59, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =49;
update ingredients set carbon_foot_print =5.45, water_foot_print = 5253, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =59;

insert into ingredients_name_alias values (1,'BRIE');
insert into ingredients_name_alias values (11,'ROQUEFORT');
insert into ingredients_name_alias values (121,'CHEESE BLUE-VEINED');
insert into ingredients_name_alias values (160,'PROVOLONE');
insert into ingredients_name_alias values (177,'GOUDA');
insert into ingredients_name_alias values (212,'FETA');
insert into ingredients_name_alias values (320,'NEUFCHATEL');
insert into ingredients_name_alias values (178,'GRUYERE');
insert into ingredients_name_alias values (305,'SALSA');
insert into ingredients_name_alias values (41,'LEEKS');
insert into ingredients_name_alias values (60,'PARSNIPS');
insert into ingredients_name_alias values (18,'NECTARINES');#CFP TYPOLOGY FRUIT OPENFIELD
insert into ingredients_name_alias values (49,'FONTINA CHEESE');
insert into ingredients_name_alias values (59,'CREAMED COTTAGE CHEESE');

#INFORMATION RETRIEVED USING MEDIAN FROM TYPOLOGY (TYPOLOGY AUTOMATICALLY RETRIEVED USING EMBEDDING COMPARISON)######################################################################
update ingredients set carbon_foot_print =2.11, water_foot_print = 6792, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =4;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3087.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =45;
update ingredients set carbon_foot_print =1.48, water_foot_print = 806.6, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =46;
update ingredients set carbon_foot_print =0.81, water_foot_print = 2636.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =54;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3087.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =74;
update ingredients set carbon_foot_print =2.11, water_foot_print = 6792, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =75;
update ingredients set carbon_foot_print =2.26, water_foot_print = 750.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =78;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =86;
update ingredients set carbon_foot_print =2.11, water_foot_print = 6792, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =110;
update ingredients set carbon_foot_print =0.86, water_foot_print = 901.8, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =125;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3087.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =129;
update ingredients set carbon_foot_print =0.86, water_foot_print = 901.8, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =135;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =169;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =210;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =217;
update ingredients set carbon_foot_print =3.88, water_foot_print = 3152, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =256;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =276;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3087.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =278;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3087.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =287;
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =335;
update ingredients set carbon_foot_print =2.55, water_foot_print = 1540, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =341;
update ingredients set carbon_foot_print =1.47, water_foot_print = 1870.3, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =515;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =517;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =518;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =520;
update ingredients set carbon_foot_print =1.32, water_foot_print = 2523, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =150;
update ingredients set carbon_foot_print =1.32, water_foot_print = 2523, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =232;
update ingredients set carbon_foot_print =1.48, water_foot_print = 806.6, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =240;
update ingredients set carbon_foot_print =2.64, water_foot_print = 2196.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =298;

insert into ingredients_name_alias values (4,'SAFFLOWER OIL');
insert into ingredients_name_alias values (45,'PUMPKIN SEEDS');
insert into ingredients_name_alias values (46,'CANNED SAUERKRAUT');
insert into ingredients_name_alias values (54,'GOJI BERRIES DRIED');
insert into ingredients_name_alias values (74,'SEEDS CHIA DRIED');
insert into ingredients_name_alias values (75,'CANOLA OIL');
insert into ingredients_name_alias values (78,'EDAMAME FROZEN');
insert into ingredients_name_alias values (86,'BALSAMIC VINAIGRETTE');
insert into ingredients_name_alias values (110,'SESAME OIL');
insert into ingredients_name_alias values (125,'BREAD CRUMBS');
insert into ingredients_name_alias values (129,'CARAWAY SEED');
insert into ingredients_name_alias values (135,'ITALIAN BREADCRUMBS');
insert into ingredients_name_alias values (169,'LIME JUICE');
insert into ingredients_name_alias values (210,'POMEGRANATE JUICE');
insert into ingredients_name_alias values (217,'PASSION-FRUIT JUICE');
insert into ingredients_name_alias values (256,'CHICKEN LIVER ALL CLASSES RAW');
insert into ingredients_name_alias values (276,'LEMON JUICE');
insert into ingredients_name_alias values (278,'HEMP SEEDS');
insert into ingredients_name_alias values (287,'FLAXSEED');
insert into ingredients_name_alias values (335,'CANDIES WHITE CHOCOLATE');
insert into ingredients_name_alias values (341,'GREEK YOGURT');
insert into ingredients_name_alias values (515,'BUTTERMILK BISCUIT');
insert into ingredients_name_alias values (517,'CAESAR SALAD DRESSING');
insert into ingredients_name_alias values (518,'ITALIAN SALAD DRESSING');
insert into ingredients_name_alias values (520,'SALAD DRESSING');
insert into ingredients_name_alias values (150,'CAROB FLOUR');
insert into ingredients_name_alias values (232,'CHICKPEA FLOUR');
insert into ingredients_name_alias values (240,'CAPERS CANNED');
insert into ingredients_name_alias values (298,'GRANOLA CEREALS GRANOLA');

#TYPOLOGY BASED UPDATES DERIVED MANUALLY IMPOSING THE RIGHT MATCH (SINCE PREVIOUS ALGORITHM WAS UNSECCSESSFUL)
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =2;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =14;
update ingredients set carbon_foot_print =0.98, water_foot_print = 1258, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =23;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =29;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =34;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =37;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =39;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =51;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =53;
update ingredients set carbon_foot_print =5.67, water_foot_print = 1856, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =77;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =88;
update ingredients set carbon_foot_print =0.86, water_foot_print = 901.8, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =89;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =92;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =93;
update ingredients set carbon_foot_print =2.86, water_foot_print = 1019, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =99;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =113;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =118;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =126;
update ingredients set carbon_foot_print =2.27, water_foot_print = 1724.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =136;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =138;
update ingredients set carbon_foot_print =0.52, water_foot_print = 555.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =145;
update ingredients set carbon_foot_print =1.07, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =151;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =154;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =155;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =159;
update ingredients set carbon_foot_print =2.27, water_foot_print = 1724.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =172;
update ingredients set carbon_foot_print =5.19, water_foot_print = 2313.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =175;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =181;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =216;
update ingredients set carbon_foot_print =0.52, water_foot_print = 555.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =226;
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =239;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =249;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =265;
update ingredients set carbon_foot_print =2.11, water_foot_print = 6792, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =267;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =275;
update ingredients set carbon_foot_print =1.47, water_foot_print = 1870.3, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =288;
update ingredients set carbon_foot_print =2.27, water_foot_print = 1724.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =291;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =302;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =317;
update ingredients set carbon_foot_print =0.27, water_foot_print = 554.8, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =325;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =333;
update ingredients set carbon_foot_print =1.46, water_foot_print = 572, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =337;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =339;
update ingredients set carbon_foot_print =0.88, water_foot_print = 3087.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =521;
update ingredients set carbon_foot_print =3.16, water_foot_print = 20717, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =522;
update ingredients set carbon_foot_print =1.11, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =42;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =61;
update ingredients set carbon_foot_print =1.11, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =79;
update ingredients set carbon_foot_print =0.33, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =116;
update ingredients set carbon_foot_print =0.33, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =124;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =144;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =148;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =174;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =223;
update ingredients set carbon_foot_print =0.84, water_foot_print = 8280, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =261;
update ingredients set carbon_foot_print =1.11, water_foot_print = 11264, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =274;
update ingredients set carbon_foot_print =0.33, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =284;
update ingredients set carbon_foot_print =3.88, water_foot_print = 4325, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =295;

insert into ingredients_name_alias values (2,'BARBECUE SAUCE');
insert into ingredients_name_alias values (14,'PUMPKIN PIE SPICE');
insert into ingredients_name_alias values (23,'CROUTONS');
insert into ingredients_name_alias values (29,'TABASCO');
insert into ingredients_name_alias values (34,'LEMONADE');
insert into ingredients_name_alias values (37,'CHILI POWDER');
insert into ingredients_name_alias values (39,'HOT CHILE SRIRACHA SAUCE');
insert into ingredients_name_alias values (51,'DRIED ROSEMARY');
insert into ingredients_name_alias values (53,'ONION POWDER');
insert into ingredients_name_alias values (77,'SCALLOP');
insert into ingredients_name_alias values (88,'CAJUN SEASONING');
insert into ingredients_name_alias values (89,'PRETZELS UNSALTED');
insert into ingredients_name_alias values (92,'SPICES BAY LEAF');
insert into ingredients_name_alias values (93,'DRIED PARSLEY');
insert into ingredients_name_alias values (99,'LIMEADE');
insert into ingredients_name_alias values (113,'SPICES CURRY POWDER');
insert into ingredients_name_alias values (118,'HOISIN SAUCE');
insert into ingredients_name_alias values (126,'STEAK SEASONING');
insert into ingredients_name_alias values (136,'MEATLESS BACON');
insert into ingredients_name_alias values (138,'PAPRIKA');
insert into ingredients_name_alias values (145,'TAMARINDS');
insert into ingredients_name_alias values (151,'KUMQUATS'); #FRUIT IMPORTED AS CFP TYPOLOGY
insert into ingredients_name_alias values (154,'GARLIC CHILI SAUCE');
insert into ingredients_name_alias values (155,'WEI-CHUAN FIVE SPICE POWDER');
insert into ingredients_name_alias values (159,'WORCESTERSHIRE SAUCE');
insert into ingredients_name_alias values (172,'MEATLESS MEATBALLS');
insert into ingredients_name_alias values (175,'HALIBUT FISH');
insert into ingredients_name_alias values (181,'CUMIN SEED');
insert into ingredients_name_alias values (216,'DRIED MARJORAM');
insert into ingredients_name_alias values (226,'BEANS KIDNEY');
insert into ingredients_name_alias values (239,'CHOCOLATE BAKING CHIPS');
insert into ingredients_name_alias values (249,'SPICES FENUGREEK SEED');
insert into ingredients_name_alias values (265,'SPICY BUFFALO SAUCE');
insert into ingredients_name_alias values (267,'CORN PEANUT AND OLIVE OIL');
insert into ingredients_name_alias values (275,'DRIED TARRAGON');
insert into ingredients_name_alias values (288,'VANILLA WAFERS');
insert into ingredients_name_alias values (291,'EGG SUBSTITUTE POWDER');
insert into ingredients_name_alias values (302,'SPICES OREGANO DRIED');
insert into ingredients_name_alias values (317,'YELLOW MUSTARD');
insert into ingredients_name_alias values (325,'WASABI ROOT');
insert into ingredients_name_alias values (333,'TURMERIC');
insert into ingredients_name_alias values (337,'HOT PEPPERS SAUCE');
insert into ingredients_name_alias values (339,'DRIED THYME');
insert into ingredients_name_alias values (521,'SESAME SEEDS');
insert into ingredients_name_alias values (522,'SEMI-SWEET CHOCOLATE BAKING CHIPS');
insert into ingredients_name_alias values (42,'DRIED NUTS PINE');#SHELLED NUTS AS WFP TYPOLOGY
insert into ingredients_name_alias values (61,'RED PEPPER OR CAYENNE SPICES');
insert into ingredients_name_alias values (79,'MACADAMIA NUTS');#SHELLED NUTS AS WFP TYPOLOGY
insert into ingredients_name_alias values (116,'KALE');#VEGETABLES OPENFIELD AS CFP TYPOLOGY
insert into ingredients_name_alias values (124,'CHIVES');#VEGETABLES OPENFIELD AS CFP TYPOLOGY
insert into ingredients_name_alias values (144,'FRESH DILL WEED');
insert into ingredients_name_alias values (148,'FRESH PARSLEY');
insert into ingredients_name_alias values (174,'BLACK PEPPER SPICES');
insert into ingredients_name_alias values (223,'DRIED BASIL');
insert into ingredients_name_alias values (261,'DRIED CHILE PEPPERS');
insert into ingredients_name_alias values (274,'PECANS NUTS');#SHELLED NUTS AS WFP TYPOLOGY
insert into ingredients_name_alias values (284,'ARUGULA');#VEGETABLES OPENFIELD AS CFP TYPOLOGY
insert into ingredients_name_alias values (295,'FROZEN CHICKEN FETTUCCINE');

#AUTOMATICALLY DERIVED MATCHES FOR NEW INSERTED ALTERNATIVE INGREDIENTS
update ingredients set carbon_foot_print =0.91, water_foot_print = 41, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =523;
update ingredients set carbon_foot_print =1.61, water_foot_print = 2313.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =524;
update ingredients set carbon_foot_print =2.67, water_foot_print = 237, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =525;
update ingredients set carbon_foot_print =1.43, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =526;
update ingredients set carbon_foot_print =0.82, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =527;
update ingredients set carbon_foot_print =1.07, water_foot_print = 413, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =528;
update ingredients set carbon_foot_print =1.18, water_foot_print = 748, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =529;
update ingredients set carbon_foot_print =0.81, water_foot_print = 575, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =530;
update ingredients set carbon_foot_print =1.09, water_foot_print = 1805, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =531;
update ingredients set carbon_foot_print =0.28, water_foot_print = 555.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =532;
update ingredients set carbon_foot_print =0.55, water_foot_print = 255, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =533;
update ingredients set carbon_foot_print =1.18, water_foot_print = 379, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =534;
update ingredients set carbon_foot_print =15.07, water_foot_print = 1856, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =535;
update ingredients set carbon_foot_print =3.03, water_foot_print = 2313.5, carbon_foot_print_source	= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight = 1000 where ingredient_id =536;
update ingredients set carbon_foot_print =0.81, water_foot_print = 834, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =537;
update ingredients set carbon_foot_print =1.18, water_foot_print = 336, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =538;
update ingredients set carbon_foot_print =2.43, water_foot_print = 41, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =539;
update ingredients set carbon_foot_print =2.88, water_foot_print = 413, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =540;
update ingredients set carbon_foot_print =2.88, water_foot_print = 413, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =541;
update ingredients set carbon_foot_print =3.73, water_foot_print = 379, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =542;
update ingredients set carbon_foot_print =0.81, water_foot_print = 750.5, carbon_foot_print_source= 'sueatable', carbon_foot_print_weight=1000, water_foot_print_source= 'sueatable', water_foot_print_weight =1000 where ingredient_id =543;

insert into ingredients_name_alias values (523,'TOMATO (g)');
insert into ingredients_name_alias values (524,'SALMON (F)');
insert into ingredients_name_alias values (525,'LETTUCE (G)');
insert into ingredients_name_alias values (526,'MELON (g)*');
insert into ingredients_name_alias values (527,'BANANA (I)');
insert into ingredients_name_alias values (528,'STRAWBERRY (I)');
insert into ingredients_name_alias values (529,'RASPBERRIES (F)*');
insert into ingredients_name_alias values (530,'POTATOES (F)');
insert into ingredients_name_alias values (531,'AVOCADO (I)');
insert into ingredients_name_alias values (532,'GREEN BEAN (fresh) (g)*');
insert into ingredients_name_alias values (533,'PINEAPPLE (I)');
insert into ingredients_name_alias values (534,'PEPPER (g)');
insert into ingredients_name_alias values (535,'PRAWNS/SHRIMPS (F)');
insert into ingredients_name_alias values (536,'COD (F)');
insert into ingredients_name_alias values (537,'SPINACH (F)');
insert into ingredients_name_alias values (538,'ZUCCHINI (g)');
insert into ingredients_name_alias values (539,'TOMATO (G)');
insert into ingredients_name_alias values (540,'STRAWBERRY (G)');
insert into ingredients_name_alias values (541,'RASPBERRY (G)');
insert into ingredients_name_alias values (542,'PEPPER (G)');
insert into ingredients_name_alias values (543,'ZUCCHINI (F)');

update ingredients set updated_at = sysdate();
commit;